### ISSUE TITLE
Install NPM 

### ISSUE THREAD

**Issue by morozj01** [nyu-software-engineering/news-aggregator#9]
All members of the team should install the default package manager for NodeJS and begin familiarizing themselves with the most common commands. 

### Work Estimate
L

**Comment by bloombar** [comment]
@nyu-software-engineering/spring-2019-news-aggregator - each team member must do this independently on their own machines.  So this should be made into 4 different duplicate Spikes - one assigned to each team member since one person working on this does not mean the others don't also have to do it.   As it now stands, if @arushi-g installs NPM and moves this to the Done column in the Task Board, that would indicate that all team members have done this, which may not be correct.  So as it is, your Task Board is misleading at best and needs to be made to accurately reflect the work that the team is doing and where it stands.  The same comment applies to any other Spikes that you each have to do independently.
